#Question :

#Each new term in the Fibonacci sequence is generated by adding the previous two terms.
#By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.


list_of_number = [1,1]
while True :
    sum_adad = list_of_number.append(sum(list_of_number[-2:]))
    if list_of_number[-1] >= 4000000 :
        break
print(sum(list_of_number[2::3]))

#output : 4613732 